Run inline

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,2 +1,11 @@
 #!/bin/bash
+
+# Check if the PYCODE environment variable is set
+if [ -z "$PYCODE" ]; then
+    echo "Error: PYCODE environment variable is not set."
+    exit 1
+fi
+
+# Run the Python code specified in the PYCODE variable
 python3 -c "$PYCODE"
+
